version: '3.9'

services:

  back:
    restart: unless-stopped
    build: .
    command: uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - .env 
    networks:
      - db-network


  db:
    image: postgres:14-alpine
    container_name: marketplace_db
    restart: unless-stopped
    volumes:
      - ../data/storage/data:/var/lib/postgresql/data
    networks:
      - db-network
    expose:
      - 5432
    env_file:
      - .env 


networks:
  db-network:
    driver: bridge