"""07-17:15:09

Revision ID: 3da4de1789be
Revises: de964c6dc207
Create Date: 2023-07-17 09:10:09.124104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da4de1789be'
down_revision = 'de964c6dc207'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('type', sa.String(), nullable=True))
    op.add_column('products', sa.Column('origin', sa.String(), nullable=True))
    op.add_column('products', sa.Column('certification', sa.String(), nullable=True))
    op.add_column('products', sa.Column('color', sa.String(), nullable=True))
    op.add_column('products', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_products_certification'), 'products', ['certification'], unique=False)
    op.create_index(op.f('ix_products_color'), 'products', ['color'], unique=False)
    op.create_index(op.f('ix_products_origin'), 'products', ['origin'], unique=False)
    op.create_index(op.f('ix_products_type'), 'products', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_type'), table_name='products')
    op.drop_index(op.f('ix_products_origin'), table_name='products')
    op.drop_index(op.f('ix_products_color'), table_name='products')
    op.drop_index(op.f('ix_products_certification'), table_name='products')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'price')
    op.drop_column('products', 'color')
    op.drop_column('products', 'certification')
    op.drop_column('products', 'origin')
    op.drop_column('products', 'type')
    # ### end Alembic commands ###
